### PR TITLE
GRAPHICS-19: Football and simplified storybook setup (Graphics workflow demo)

### PR DESCRIPTION
**Pull request by thekingofjibs**

### CODE REVIEW

**Comment by markspolakovs** [comment]
Har har I stole your branch

**Comment by markspolakovs** [comment]
@thekingofjibs how do you feel about merging this now in the state that it's in, so we have something for training?

**Comment by thekingofjibs** [comment]
> @thekingofjibs how do you feel about merging this now in the state that it's in, so we have something for training?

I mean hopefully I can merge in my changes before training still but sure why not, go for it👍👍

**Comment by markspolakovs** [comment]
> > @thekingofjibs how do you feel about merging this now in the state that it's in, so we have something for training?
> 
> I mean hopefully I can merge in my changes before training still but sure why not, go for it👍👍

If you think you can get them in early-mid afternoon go for it and promote it to prod yourself, then it's on you if you break it :p

**Pull request merged**
